# Generated by Django 5.2.6 on 2025-09-26 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_movie_delete_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Drama',
        ),
    ]
