# Generated by Django 5.2.6 on 2025-09-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_movie_drama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drama',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
